-- Employee master seed for CodeAge Pvt. Ltd.
-- Generated from December Salaries.xlsx on 2026-04-09.
-- Import this first so attendance can bind to existing employee IDs.
SET NAMES utf8mb4;

-- Base reference data.
INSERT INTO `departments` (`name`, `total_employees`, `created_at`, `updated_at`)
SELECT 'Unassigned', 0, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM `departments` WHERE `name` = 'Unassigned');

-- Employee ID configuration stays aligned with the imported workbook.
INSERT INTO `settings` (`key`, `value`, `created_at`, `updated_at`) VALUES ('employee_id_prefix', 'CA-E-', NOW(), NOW())
ON DUPLICATE KEY UPDATE `value` = CASE WHEN `value` IS NULL OR `value` = '' THEN 'CA-E-' ELSE `value` END, `updated_at` = NOW();
INSERT INTO `settings` (`key`, `value`, `created_at`, `updated_at`) VALUES ('employee_id_counter', '44', NOW(), NOW())
ON DUPLICATE KEY UPDATE `value` = CASE WHEN CAST(`value` AS UNSIGNED) < 44 THEN '44' ELSE `value` END, `updated_at` = NOW();

-- Employee master upserts.
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Kainat Javed', 'kainatj283@gmail.com', 'CA-E-02', 'SEO Executive', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '6110141104012', '03435788229', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Hamza Mushtaq', 'hm136890@gmail.com', 'CA-E-03', 'WordPress & Shopify Developer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3720112056085', '03125705808', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Dil Awaiz', 'officialdilawaiz23@gmail.com', 'CA-E-04', 'WordPress Developer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3630258928072', '03000965852', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Kumail Abbas', 'donati1122@gmail.com', 'CA-E-05', 'wordpress developer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '7170403436973', '03134397647', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad Rehan', 'Rehanshalian@gmail.com', 'CA-E-08', 'Senior WordPress Developer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740251442857', '03495015617', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad Rehan Atta', 'bodlarehan@gmail.com', 'CA-E-09', 'SEO Team Assistance', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740596980395', '03025155881', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Mahshan Awan', 'mahshanawan@gmail.com', 'CA-E-10', 'SEO Team Lead', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740590024105', '03314497751', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad Faizan Butt', 'faizanb843@gmail.com', 'CA-E-11', 'SEO Expert', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '6110117249967', '03409191420', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad imran gul', 'imrangull204@gmail.com', 'CA-E-13', 'SEO', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '6110168337893', '03421579816', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad Ghufran', 'ghuffy5643@gmail.com', 'CA-E-14', 'SEO Expert', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740555520447', '03315365166', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Hassan Raza', 'hrcreationpro@gmail.com', 'CA-E-18', 'Graphic Designer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740187255873', '03414733460', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Ans Dilshad', 'ans.dilshadwp@gmail.com', 'CA-E-19', 'Wordpress Developer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740552031021', '03115790595', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Bilal Ahmed', 'bilalahmedgt4@gmail.com', 'CA-E-20', 'Project Manager/Team Lead', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740630187509', '03065291523', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('MUHAMMAD ARMAN', 'armanseo0001@gmail.com', 'CA-E-22', 'Seo Expert', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740504182019', '03215364593', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Sana Ahmed', 'sahmedk05@gmail.com', 'CA-E-26', 'Web Content Writer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740520471614', '03215656569', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Sidra Khan', 'jsidrakhan71@gmail.com', 'CA-E-27', 'HR Manager', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740578877180', '03155841826', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Hashmul Hussan Qurashi', 'ca-e-28@imported.codeage.local', 'CA-E-28', 'Office Boy', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740509303245', '03345252287', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09. Placeholder email assigned because the workbook email field was blank.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Sibgha Nawaz', 'sibgha.nawaz@gmail.com', 'CA-E-29', 'Business Developer and Content Writer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '6110157205490', '03235455577', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad Saad Mubeen', 'msaadmubeen02@gmail.com', 'CA-E-32', 'Web Developer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740549180849', '03418963064', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Sikandar Ayub', 'sikandarayub007@gmail.com', 'CA-E-33', 'Social media ads marketer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740560195179', '03350012290', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Muhammad Shafiq Ur Rehman', 'Shafiqprince1122@gmail.com', 'CA-E-36', 'Social media ads Intern', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3210214770555', '03346700530', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Salman Saeed', 'salmansaeed.2681@gmail.com', 'CA-E-38', 'Appointment setter', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '6110179642131', '03366933331', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Zeeshan ali', 'zeeshanali.cuiwah@gmail.com', 'CA-E-41', 'Google Ads Specialist', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3740658506029', '03075212326', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Hanan Iqbal', 'hananmalik364@gmail.com', 'CA-E-43', 'Ul/UX Designer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3730224010815', '03414992894', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();
INSERT INTO `employees` (`full_name`, `email`, `employee_id`, `designation`, `department_id`, `status`, `hiring_date`, `cnic`, `phone`, `gender`, `payroll_status`, `hr_comments`, `created_at`, `updated_at`) VALUES ('Nazia Akhtar', 'nazia.inbox@gmail.com', 'CA-E-44', 'SEO intern and content writer', (SELECT `id` FROM `departments` WHERE `name` = 'Unassigned' ORDER BY `id` ASC LIMIT 1), 'active', NULL, '3520223775132', '03349961161', NULL, 'Paid', 'Imported from December Salaries.xlsx workbook on 2026-04-09.', NOW(), NOW())
ON DUPLICATE KEY UPDATE `full_name` = VALUES(`full_name`), `designation` = VALUES(`designation`), `department_id` = VALUES(`department_id`), `status` = VALUES(`status`), `cnic` = VALUES(`cnic`), `phone` = VALUES(`phone`), `payroll_status` = VALUES(`payroll_status`), `hr_comments` = VALUES(`hr_comments`), `updated_at` = NOW();


